### ISSUE TITLE
Descrivere la gestione del flash

### ISSUE THREAD

**Issue by mzanella** [Augugrumi/GhioCA-Paper#12]
Nel paper c'è scritto che si può solamente spegnere il flash. Dare una descrizione più esaustiva.

**Comment by Polpetta** [comment]
Possiamo chiudere?

**Comment by tfederico** [comment]
Non sapevo neanche dell'esistenza di questa issue

**Comment by Polpetta** [comment]
Non si smette mai di imparare nella vita

**Comment by tfederico** [comment]
Tra l'altro estremamente dettagliata

**Comment by Polpetta** [comment]
Gia'
